# Generated by Django 5.1.3 on 2024-11-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Created_at", models.DateField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=260)),
                ("emali", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=12)),
                ("adress", models.CharField(max_length=10000)),
                ("city", models.CharField(max_length=290)),
                ("state", models.CharField(max_length=390)),
                ("zipcod", models.CharField(max_length=50)),
            ],
        ),
    ]
